name: Deploy to Byethost
on:
  push:
    branches: [ "main" ]   # Khi bạn push lên nhánh main thì tự deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Upload to Byethost with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOST }} #chỗ này phụ thuộc đặt như thế nào trong secret variable(action)
        username: ${{ secrets.USER }} #chỗ này phụ thuộc đặt như thế nào trong secret variable(action)
        password: ${{ secrets.PW }} #chỗ này phụ thuộc đặt như thế nào trong secret variable(action)
        local-dir: ./        # Thư mục website trong repo
        server-dir: /quysinhdongvien2025daihoigioitre.22web.org/htdocs/  # Thư mục website trên Byethost
